import { Flight } from '../types/flight';
import { FlightNormalizer } from './flightNormalizer';

export const MOCK_FLIGHTS_RAW = [
  {
    flight_date: new Date().toISOString().split('T')[0],
    flight_status: 'active',
    departure: {
      airport: 'Rajiv Gandhi International Airport',
      timezone: 'Asia/Kolkata',
      iata: 'HYD',
      icao: 'VOHS',
      terminal: '1',
      gate: '24B',
      baggage: '4',
      delay: 15,
      scheduled: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      actual: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    arrival: {
      airport: 'Indira Gandhi International Airport',
      timezone: 'Asia/Kolkata',
      iata: 'DEL',
      icao: 'VIDP',
      terminal: '3',
      gate: '48A',
      baggage: '8',
      delay: 10,
      scheduled: new Date(Date.now() + 75 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() + 85 * 60 * 1000).toISOString(),
      actual: null,
    },
    airline: {
      name: 'Air India',
      iata: 'AI',
      icao: 'AIC',
    },
    flight: {
      number: '101',
      iata: 'AI101',
      icao: 'AIC101',
    },
    aircraft: {
      registration: 'VT-EXQ',
      iata: 'A320',
      icao: 'A20N',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 22.8994,
      longitude: 77.7645,
      altitude: 34000,
      direction: 350,
      speed_horizontal: 840,
      speed_vertical: 0,
      is_ground: false,
    },
  },
  {
    flight_date: new Date().toISOString().split('T')[0],
    flight_status: 'active',
    departure: {
      airport: 'Chhatrapati Shivaji Maharaj International Airport',
      timezone: 'Asia/Kolkata',
      iata: 'BOM',
      icao: 'VABB',
      terminal: '2',
      gate: '12',
      baggage: '3',
      delay: null,
      scheduled: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      actual: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    },
    arrival: {
      airport: 'Kempegowda International Airport',
      timezone: 'Asia/Kolkata',
      iata: 'BLR',
      icao: 'VOBL',
      terminal: '1',
      gate: '6',
      baggage: '2',
      delay: null,
      scheduled: new Date(Date.now() + 55 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() + 52 * 60 * 1000).toISOString(),
      actual: null,
    },
    airline: {
      name: 'IndiGo',
      iata: '6E',
      icao: 'IGO',
    },
    flight: {
      number: '502',
      iata: '6E502',
      icao: 'IGO502',
    },
    aircraft: {
      registration: 'VT-IZR',
      iata: 'A321',
      icao: 'A21N',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 16.1441,
      longitude: 75.2974,
      altitude: 31000,
      direction: 145,
      speed_horizontal: 780,
      speed_vertical: 0,
      is_ground: false,
    },
  },
  {
    flight_date: new Date().toISOString().split('T')[0],
    flight_status: 'scheduled',
    departure: {
      airport: 'London Heathrow Airport',
      timezone: 'Europe/London',
      iata: 'LHR',
      icao: 'EGLL',
      terminal: '5',
      gate: 'B32',
      baggage: null,
      delay: 0,
      scheduled: new Date(Date.now() + 180 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() + 180 * 60 * 1000).toISOString(),
      actual: null,
    },
    arrival: {
      airport: 'John F. Kennedy International Airport',
      timezone: 'America/New_York',
      iata: 'JFK',
      icao: 'KJFK',
      terminal: '7',
      gate: '14',
      baggage: '5',
      delay: null,
      scheduled: new Date(Date.now() + 660 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() + 660 * 60 * 1000).toISOString(),
      actual: null,
    },
    airline: {
      name: 'British Airways',
      iata: 'BA',
      icao: 'BAW',
    },
    flight: {
      number: '249',
      iata: 'BA249',
      icao: 'BAW249',
    },
    aircraft: {
      registration: 'G-XWBG',
      iata: 'A350',
      icao: 'A35K',
    },
    live: null, // No live data before departure
  },
  {
    flight_date: new Date().toISOString().split('T')[0],
    flight_status: 'landed',
    departure: {
      airport: 'Dubai International Airport',
      timezone: 'Asia/Dubai',
      iata: 'DXB',
      icao: 'OMDB',
      terminal: '3',
      gate: 'B10',
      baggage: '1',
      delay: 0,
      scheduled: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() - 360 * 60 * 1000).toISOString(),
      actual: new Date(Date.now() - 355 * 60 * 1000).toISOString(),
    },
    arrival: {
      airport: 'Rajiv Gandhi International Airport',
      timezone: 'Asia/Kolkata',
      iata: 'HYD',
      icao: 'VOHS',
      terminal: '1',
      gate: '18',
      baggage: '7',
      delay: -10,
      scheduled: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
      actual: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    },
    airline: {
      name: 'Emirates',
      iata: 'EK',
      icao: 'UAE',
    },
    flight: {
      number: '505',
      iata: 'EK505',
      icao: 'UAE505',
    },
    aircraft: {
      registration: 'A6-EEO',
      iata: 'B777',
      icao: 'B77W',
    },
    live: null,
  },
  {
    flight_date: new Date().toISOString().split('T')[0],
    flight_status: 'delayed',
    departure: {
      airport: 'Singapore Changi Airport',
      timezone: 'Asia/Singapore',
      iata: 'SIN',
      icao: 'WSSS',
      terminal: '2',
      gate: 'F40',
      baggage: '9',
      delay: 55,
      scheduled: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() + 115 * 60 * 1000).toISOString(),
      actual: null,
    },
    arrival: {
      airport: 'Chennai International Airport',
      timezone: 'Asia/Kolkata',
      iata: 'MAA',
      icao: 'VOMM',
      terminal: '4',
      gate: '3',
      baggage: '4',
      delay: 50,
      scheduled: new Date(Date.now() + 280 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() + 330 * 60 * 1000).toISOString(),
      actual: null,
    },
    airline: {
      name: 'Singapore Airlines',
      iata: 'SQ',
      icao: 'SIA',
    },
    flight: {
      number: '401',
      iata: 'SQ401',
      icao: 'SIA401',
    },
    aircraft: {
      registration: '9V-SHI',
      iata: 'A350',
      icao: 'A359',
    },
    live: null,
  },
  {
    flight_date: new Date().toISOString().split('T')[0],
    flight_status: 'active',
    departure: {
      airport: 'John F. Kennedy International Airport',
      timezone: 'America/New_York',
      iata: 'JFK',
      icao: 'KJFK',
      terminal: '8',
      gate: '31',
      baggage: '2',
      delay: 5,
      scheduled: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() - 115 * 60 * 1000).toISOString(),
      actual: new Date(Date.now() - 115 * 60 * 1000).toISOString(),
    },
    arrival: {
      airport: 'Los Angeles International Airport',
      timezone: 'America/Los_Angeles',
      iata: 'LAX',
      icao: 'KLAX',
      terminal: '4',
      gate: '42B',
      baggage: '6',
      delay: null,
      scheduled: new Date(Date.now() + 220 * 60 * 1000).toISOString(),
      estimated: new Date(Date.now() + 215 * 60 * 1000).toISOString(),
      actual: null,
    },
    airline: {
      name: 'American Airlines',
      iata: 'AA',
      icao: 'AAL',
    },
    flight: {
      number: '100',
      iata: 'AA100',
      icao: 'AAL100',
    },
    aircraft: {
      registration: 'N787AA',
      iata: 'B789',
      icao: 'B789',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 38.6270,
      longitude: -90.1994,
      altitude: 36000,
      direction: 255,
      speed_horizontal: 890,
      speed_vertical: 0,
      is_ground: false,
    },
  },
];

export function getMockFlights(): Flight[] {
  return MOCK_FLIGHTS_RAW.map(raw => FlightNormalizer.normalizeAviationStack(raw));
}
